INSERT INTO regiones (id, nombre) VALUES ('1', 'Sudamérica');
INSERT INTO regiones (id, nombre) VALUES ('2', 'Centroamérica');
INSERT INTO regiones (id, nombre) VALUES ('3', 'Norteamérica');
INSERT INTO regiones (id, nombre) VALUES ('4', 'Europa');
INSERT INTO regiones (id, nombre) VALUES ('5', 'Asia');
INSERT INTO regiones (id, nombre) VALUES ('6', 'Africa');
INSERT INTO regiones (id, nombre) VALUES ('7', 'Oceanía');

INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', 1, '2018-01-01');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', 2, '2018-01-02');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', 3, '2018-01-03');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', 4, '2018-01-04');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', 5, '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', 6, '2018-02-10');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', 7, '2018-02-18');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', 1, '2018-02-28');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', 2, '2018-03-03');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', 3, '2018-03-04');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', 4, '2018-03-05');
INSERT INTO clientes (nombre, apellido, email, region_id, created_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', 5, '2018-03-06');